"""Add intent to RagRequestLog

Revision ID: 7b0dfff5ba36
Revises: 1f9366c1629a
Create Date: 2026-06-29 10:33:27.109090+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b0dfff5ba36'
down_revision: Union[str, None] = '1f9366c1629a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_request_logs', sa.Column('intent', sa.String(), nullable=True))
    op.create_index(op.f('ix_rag_request_logs_intent'), 'rag_request_logs', ['intent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_request_logs_intent'), table_name='rag_request_logs')
    op.drop_column('rag_request_logs', 'intent')
    # ### end Alembic commands ###
