"""Add cache_latency_ms to RagRequestLog

Revision ID: 1f9366c1629a
Revises: cc95b8a22174
Create Date: 2026-06-29 09:54:09.978543+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f9366c1629a'
down_revision: Union[str, None] = 'cc95b8a22174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_request_logs', sa.Column('cache_latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_request_logs', 'cache_latency_ms')
    # ### end Alembic commands ###
