"""Add cache and generation latency to BasicRequestLog

Revision ID: cc95b8a22174
Revises: 0004
Create Date: 2026-06-29 08:57:50.852736+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc95b8a22174'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_request_logs', sa.Column('cache_latency_ms', sa.Float(), nullable=True))
    op.add_column('basic_request_logs', sa.Column('generation_latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basic_request_logs', 'generation_latency_ms')
    op.drop_column('basic_request_logs', 'cache_latency_ms')
    # ### end Alembic commands ###
